### ISSUE TITLE
how to use?

### ISSUE THREAD

**Issue by sakgoyal** [alvinhochun/touchpad-handwriting#1]
how do I use this? I believe I have windows precision drivers.

**Comment by alvinhochun** [comment]
This application only supports Synaptics touchpads with the Synaptics drivers installed.

This is unrelated to Windows Precision Touchpad (PTP), as the two are not mutually exclusive. Synaptics touchpads may or may not support PTP. Any PTP may or may not be a Synaptics touchpad.

That is, if the touchpad of your device is manufactured by Synaptics and the Synaptics driver is installed, this application should work (as in it can detect the touchpad and capture presses). Whether or not it is a PTP does not have any effect.

**Comment by alvinhochun** [comment]
Please find the past binary releases on SourceForge: https://sourceforge.net/projects/touchpad-hw/files/

**Comment by sakgoyal** [comment]
is there anything similar to this that works on PTP?

**Comment by alvinhochun** [comment]
None that I'm aware of.
