### ISSUE TITLE
How to use stroke jumping fix?

### ISSUE THREAD

**Issue by eao** [alvinhochun/touchpad-handwriting#2]
I see that 2 months ago a fix for stroke jumping was committed, but the exe file on sourceforge is still from 2013.  How can I download or compile (preferably just download) the new version?

**Comment by eao** [comment]
Figured it out myself.  Just install Visual Studio and .NET Framework 4.whatever.  Open the .sln file and right click on the solution in the solution explorer and "Build Solution".  The console tells you where the built files are.  Surprisingly easy.

This version no longer draws a line to bottom left corner on finger up.  Thanks so much for the fix!

**Comment by alvinhochun** [comment]
Glad you figured it out by yourself. I didn't publish a binary release because I thought it is not really useful any more due to how it interacts with the Precision Touchpad support in Windows 10.

Are you using it on a system with a driver that does not support Precision Touchpad?

**Comment by eao** [comment]
I am using it on a Thinkpad T450s still running Windows 7.  I believe my touchpad drivers are Synaptics.

**Comment by alvinhochun** [comment]
Windows 7 doesn't support Precision Touchpad (it was introduced starting from Windows 8.1) so it would work as expected. Though you should know that Microsoft has ended support for Windows 7.
